[package]
name = "rust-training"
version = "0.1.0"
authors = ["thomasvergne <thomas@quark-lang.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
